DROP TABLE IF EXISTS MUTUAL_FUND_COMPANY;

CREATE TABLE MUTUAL_FUND_COMPANY (ID INT PRIMARY KEY, SYMBOL VARCHAR(50), COMPANY_NAME VARCHAR(100));

insert into MUTUAL_FUND_COMPANY values( 1	,'AAAAX'	,'DWS RREEF Real Assets Fund - Class A');
insert into MUTUAL_FUND_COMPANY values( 2	,'AAADX'	,'Aberdeen Income Builder Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 3	,'AAAGX'	,'Thrivent Large Cap Growth Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 4	,'AAAIX'	,'American Century Strategic Allocation: Aggressive Fund I Class');
insert into MUTUAL_FUND_COMPANY values( 5	,'AAANX'	,'Horizon Active Asset Allocation Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 6	,'AAAPX'	,'DWS RREEF Real Assets Fund - Class C');
insert into MUTUAL_FUND_COMPANY values( 7	,'AAAQX'	,'DWS RREEF Real Assets Fund - Class R');
insert into MUTUAL_FUND_COMPANY values( 8	,'AAARX'	,'American Century Strategic Allocation: Aggressive Fund R Class');
insert into MUTUAL_FUND_COMPANY values( 9	,'AAASX'	,'DWS RREEF Real Assets Fund - Class S');
insert into MUTUAL_FUND_COMPANY values( 10	,'AAATX'	,'American Funds 2010 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 11	,'AAAUX'	,'American Century Strategic Allocation: Aggressive Fund R6 Class');
insert into MUTUAL_FUND_COMPANY values( 12	,'AAAVX'	,'DWS RREEF Real Assets Fund - Class R6');
insert into MUTUAL_FUND_COMPANY values( 13	,'AAAWX'	,'DWS RREEF Real Assets Fund - Class T');
insert into MUTUAL_FUND_COMPANY values( 14	,'AAAZX'	,'DWS RREEF Real Assets Fund - Class Inst');
insert into MUTUAL_FUND_COMPANY values( 15	,'AABAX'	,'Cavanal Hill Active Core Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 16	,'AABCX'	,'Putnam Dynamic Asset Allocation Balanced Fund Class C');
insert into MUTUAL_FUND_COMPANY values( 17	,'AABFX'	,'Thrivent Balanced Income Plus Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 18	,'AABOX'	,'Cavanal Hill Bond Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 19	,'AABPX'	,'American Beacon Balanced Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 20	,'AABSX'	,'AllianzGI Best Styles Emerging Markets Equity Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 21	,'AABTX'	,'American Funds 2015 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 22	,'AABUX'	,'AllianzGI Best Styles U.S. Equity Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 23	,'AACBX'	,'Cavanal Hill Active Core Fund Class C');
insert into MUTUAL_FUND_COMPANY values( 24	,'AACCX'	,'American Century Strategic Allocation: Conservative Fund C Class');
insert into MUTUAL_FUND_COMPANY values( 25	,'AACDX'	,'American Century Strategic Allocation: Conservative Fund R6 Class');
insert into MUTUAL_FUND_COMPANY values( 26	,'AACFX'	,'Invesco Greater China Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 27	,'AACGX'	,'American Century Strategic Allocation: Conservative Fund R5 Class');
insert into MUTUAL_FUND_COMPANY values( 28	,'AACIX'	,'American Beacon Mid-Cap Value Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 29	,'AACOX'	,'Cavanal Hill Opportunistic Fund Class C');
insert into MUTUAL_FUND_COMPANY values( 30	,'AACRX'	,'American Century Strategic Allocation: Conservative Fund R Class');
insert into MUTUAL_FUND_COMPANY values( 31	,'AACTX'	,'American Funds 2020 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 32	,'AADAX'	,'Invesco Growth Allocation Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 33	,'AADBX'	,'American Beacon Balanced Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 34	,'AADCX'	,'Invesco Growth Allocation Fund Class C');
insert into MUTUAL_FUND_COMPANY values( 35	,'AADDX'	,'Aberdeen Income Builder Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 36	,'AADEX'	,'American Beacon Large Cap Value Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 37	,'AADGX'	,'Aasgard Dividend Growth Small & Mid-Cap Fund No Load Class');
insert into MUTUAL_FUND_COMPANY values( 38	,'AADIX'	,'Invesco Growth Allocation Fund R5 Class');
insert into MUTUAL_FUND_COMPANY values( 39	,'AADRX'	,'Invesco Growth Allocation Fund Class R');
insert into MUTUAL_FUND_COMPANY values( 40	,'AADSX'	,'Invesco Growth Allocation Fund Class S');
insert into MUTUAL_FUND_COMPANY values( 41	,'AADTX'	,'American Funds 2025 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 42	,'AADYX'	,'Invesco Growth Allocation Fund Class Y');
insert into MUTUAL_FUND_COMPANY values( 43	,'AAEMX'	,'Alger Emerging Markets Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 44	,'AAENX'	,'Cavanal Hill Strategic Enhanced Yield Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 45	,'AAERX'	,'American Beacon International Equity Fund Class R6');
insert into MUTUAL_FUND_COMPANY values( 46	,'AAESX'	,'Invesco Growth Allocation Fund Class R6');
insert into MUTUAL_FUND_COMPANY values( 47	,'AAETX'	,'American Funds 2030 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 48	,'AAFTX'	,'American Funds 2035 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 49	,'AAGOX'	,'Alger Large Cap Growth Portfolio Class I-2');
insert into MUTUAL_FUND_COMPANY values( 50	,'AAGPX'	,'American Beacon Large Cap Value Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 51	,'AAGTX'	,'American Funds 2040 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 52	,'AAHMX'	,'Aberdeen High Yield Managed Duration Municipal Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 53	,'AAHTX'	,'American Funds 2045 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 54	,'AAHYX'	,'Thrivent Diversified Income Plus Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 55	,'AAIBX'	,'Cavanal Hill Moderate Duration Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 56	,'AAIEX'	,'American Beacon International Equity Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 57	,'AAIFX'	,'Crow Point Alternative Income Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 58	,'AAIIX'	,'Ancora Income Fund Class I');
insert into MUTUAL_FUND_COMPANY values( 59	,'AAINX'	,'Thrivent Opportunity Income Plus Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 60	,'AAIPX'	,'American Beacon International Equity Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 61	,'AAISX'	,'American Beacon International Equity Fund Advisor Class');
insert into MUTUAL_FUND_COMPANY values( 62	,'AALGX'	,'Thrivent Large Cap Stock Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 63	,'AALRX'	,'American Beacon Large Cap Value Fund Class R6');
insert into MUTUAL_FUND_COMPANY values( 64	,'AALTX'	,'American Funds 2050 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 65	,'AAMAX'	,'Absolute Capital Asset Allocator Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 66	,'AAMBX'	,'Thrivent Municipal Bond Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 67	,'AAMCX'	,'Absolute Capital Asset Allocator Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 68	,'AAMIX'	,'Absolute Capital Asset Allocator Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 69	,'AAMOX'	,'Alger SMid Cap Focus Portfolio I-2');
insert into MUTUAL_FUND_COMPANY values( 70	,'AAMPX'	,'AllianzGI Micro Cap Fund Class P');
insert into MUTUAL_FUND_COMPANY values( 71	,'AAMTX'	,'American Funds 2055 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 72	,'AANTX'	,'American Funds 2060 Target Date Retirement FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 73	,'AAOPX'	,'Cavanal Hill Opportunistic Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 74	,'AAPEX'	,'Aberdeen Asia Pacific (ex-Japan) Equity Fund Institutional Service Class');
insert into MUTUAL_FUND_COMPANY values( 75	,'AAPIX'	,'Aberdeen Asia Pacific (ex-Japan) Equity Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 76	,'AARAX'	,'AB All Market Alternative Return Portfolio Class A');
insert into MUTUAL_FUND_COMPANY values( 77	,'AARCX'	,'AB All Market Alternative Return Portfolio Class C');
insert into MUTUAL_FUND_COMPANY values( 78	,'AARMX'	,'American Independence Global Tactical Allocation Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 79	,'AARYX'	,'AB All Market Alternative Return Portfolio Advisor Class');
insert into MUTUAL_FUND_COMPANY values( 80	,'AASCX'	,'Thrivent Mid Cap Stock Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 81	,'AASMX'	,'Thrivent Small Cap Stock Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 82	,'AASOX'	,'Alger Small Cap Growth Portfolio Class I-2');
insert into MUTUAL_FUND_COMPANY values( 83	,'AASRX'	,'American Beacon Small Cap Value Fund R6 Class');
insert into MUTUAL_FUND_COMPANY values( 84	,'AASSX'	,'American Beacon Small Cap Value Fund Advisor Class');
insert into MUTUAL_FUND_COMPANY values( 85	,'AASTX'	,'Cavanal Hill Limited Duration Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 86	,'AATIX'	,'Ancora/Thelen Small-Mid Cap Fund Class I');
insert into MUTUAL_FUND_COMPANY values( 87	,'AATSX'	,'Ancora/Thelen Small-Mid Cap Fund Class S');
insert into MUTUAL_FUND_COMPANY values( 88	,'AAUPX'	,'AllianzGI Ultra Micro Cap Fund Class P');
insert into MUTUAL_FUND_COMPANY values( 89	,'AAUSX'	,'Cavanal Hill Ultra Short Tax-Free Income Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 90	,'AAUTX'	,'Thrivent Large Cap Value Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 91	,'AAVPX'	,'AMG Managers Value Partners Asia Dividend Fund Class I');
insert into MUTUAL_FUND_COMPANY values( 92	,'AAWEX'	,'Cavanal Hill World Energy Fund A');
insert into MUTUAL_FUND_COMPANY values( 93	,'AAWVX'	,'Cavanal Mid Cap Core Equity Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 94	,'AAZAX'	,'AB Municipal Income Fund II Arizona Portfolio Class A');
insert into MUTUAL_FUND_COMPANY values( 95	,'AAZBX'	,'AB Municipal Income Fund II Arizona Portfolio Class B');
insert into MUTUAL_FUND_COMPANY values( 96	,'AAZCX'	,'AB Municipal Income Fund II Arizona Portfolio Class C');
insert into MUTUAL_FUND_COMPANY values( 97	,'ABAEX'	,'AB Emerging Markets Multi-Asset Portfolio Class A');
insert into MUTUAL_FUND_COMPANY values( 98	,'ABALX'	,'American Funds American Balanced FundÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 99	,'ABAMX'	,'AllianzGI Retirement 2030 Fund Administrative Class');
insert into MUTUAL_FUND_COMPANY values( 100	,'ABASX'	,'AB Discovery Value Fund Class A');

insert into MUTUAL_FUND_COMPANY values( 101	,'ABBSX'	,'AB Discovery Value Fund Class B');
insert into MUTUAL_FUND_COMPANY values( 102	,'ABCAX'	,'American Beacon The London Company Income Equity Fund A Class');
insert into MUTUAL_FUND_COMPANY values( 103	,'ABCCX'	,'American Beacon Balanced Fund C Class');
insert into MUTUAL_FUND_COMPANY values( 104	,'ABCEX'	,'AB Emerging Markets Multi-Asset Portfolio Class C');
insert into MUTUAL_FUND_COMPANY values( 105	,'ABCIX'	,'American Beacon The London Company Income Equity Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 106	,'ABCSX'	,'AB Discovery Value Fund Class C');
insert into MUTUAL_FUND_COMPANY values( 107	,'ABCVX'	,'American Beacon The London Company Income Equity Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 108	,'ABCYX'	,'American Beacon The London Company Income Equity Fund Y Class');
insert into MUTUAL_FUND_COMPANY values( 109	,'ABDAX'	,'Columbia Capital Allocation Conservative Portfolio Class A');
insert into MUTUAL_FUND_COMPANY values( 110	,'ABECX'	,'American Beacon The London Company Income Equity Fund C Class');
insert into MUTUAL_FUND_COMPANY values( 111	,'ABEIX'	,'Aberdeen Tax-Free Income Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 112	,'ABEMX'	,'Aberdeen Emerging Markets Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 113	,'ABERX'	,'Aberdeen Tax-Free Income Fund Class R');
insert into MUTUAL_FUND_COMPANY values( 114	,'ABESX'	,'Aberdeen Tax-Free Income Fund Institutional Service Class');
insert into MUTUAL_FUND_COMPANY values( 115	,'ABEYX'	,'American Beacon International Equity Fund Class Y');
insert into MUTUAL_FUND_COMPANY values( 116	,'ABFAX'	,'American Beacon Balanced Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 117	,'ABGNX'	,'American Century Balanced Fund R5 Class');
insert into MUTUAL_FUND_COMPANY values( 118	,'ABHFX'	,'American High-Income Municipal Bond FundÂ® Class F-1');
insert into MUTUAL_FUND_COMPANY values( 119	,'ABHIX'	,'American Century High-Yield Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 120	,'ABHTX'	,'American Century Government Bond Fund I Class');
insert into MUTUAL_FUND_COMPANY values( 121	,'ABHYX'	,'American Century High Yield Municipal Fund Investor Class');
insert into MUTUAL_FUND_COMPANY values( 122	,'ABIAX'	,'AB International Value Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 123	,'ABIBX'	,'AB International Value Fund Class B');
insert into MUTUAL_FUND_COMPANY values( 124	,'ABICX'	,'AB International Value Fund Class C');
insert into MUTUAL_FUND_COMPANY values( 125	,'ABIEX'	,'AB Emerging Markets Multi-Asset Portfolio Class I');
insert into MUTUAL_FUND_COMPANY values( 126	,'ABIMX'	,'AB Impact Municipal Income Shares');
insert into MUTUAL_FUND_COMPANY values( 127	,'ABINX'	,'American Century Balanced Fund I Class');
insert into MUTUAL_FUND_COMPANY values( 128	,'ABISX'	,'Aberdeen Asia Bond Fund Institutional Services Class');
insert into MUTUAL_FUND_COMPANY values( 129	,'ABIYX'	,'AB International Value Fund Advisor Class');
insert into MUTUAL_FUND_COMPANY values( 130	,'ABIZX'	,'AMG Managers Fairpointe Mid Cap Fund Class Z');
insert into MUTUAL_FUND_COMPANY values( 131	,'ABKEX'	,'AB Emerging Markets Multi-Asset Portfolio Class K');
insert into MUTUAL_FUND_COMPANY values( 132	,'ABKYX'	,'Invesco Moderate Allocation Fund Class Y');
insert into MUTUAL_FUND_COMPANY values( 133	,'ABLAX'	,'AllianzGI Retirement 2030 Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 134	,'ABLCX'	,'AllianzGI Retirement 2030 Fund Class C');
insert into MUTUAL_FUND_COMPANY values( 135	,'ABLIX'	,'AllianzGI Retirement 2030 Fund R6 Class');
insert into MUTUAL_FUND_COMPANY values( 136	,'ABLOX'	,'Alger Balanced Portfolio Class I-2');
insert into MUTUAL_FUND_COMPANY values( 137	,'ABLPX'	,'AllianzGI Retirement 2030 Fund Class P');
insert into MUTUAL_FUND_COMPANY values( 138	,'ABLRX'	,'AllianzGI Retirement 2030 Fund Class R');
insert into MUTUAL_FUND_COMPANY values( 139	,'ABLSX'	,'American Beacon Balanced Fund Advisor Class');
insert into MUTUAL_FUND_COMPANY values( 140	,'ABLYX'	,'American Beacon Large Cap Value Fund Class Y');
insert into MUTUAL_FUND_COMPANY values( 141	,'ABMAX'	,'American Beacon Mid-Cap Value Fund Class A');
insert into MUTUAL_FUND_COMPANY values( 142	,'ABMIX'	,'AMG Managers Fairpointe Mid Cap Fund Class I');
insert into MUTUAL_FUND_COMPANY values( 143	,'ABNAX'	,'AB Bond Inflation Strategy Class A');
insert into MUTUAL_FUND_COMPANY values( 144	,'ABNCX'	,'AB Bond Inflation Strategy Class C');
insert into MUTUAL_FUND_COMPANY values( 145	,'ABNDX'	,'American Funds The Bond Fund of AmericaÂ® Class A');
insert into MUTUAL_FUND_COMPANY values( 146	,'ABNFX'	,'American Funds The Bond Fund of AmericaÂ® Class F-2');
insert into MUTUAL_FUND_COMPANY values( 147	,'ABNIX'	,'Aberdeen International Small Cap Fund Institutional Class');
insert into MUTUAL_FUND_COMPANY values( 148	,'ABNKX'	,'AB Bond Inflation Strategy Class K');
insert into MUTUAL_FUND_COMPANY values( 149	,'ABNOX'	,'AB Bond Inflation Strategy Class 1');
insert into MUTUAL_FUND_COMPANY values( 150	,'ABNRX'	,'AB Bond Inflation Strategy Class R');

TRUNCATE TABLE USER;
INSERT INTO User (id, username, password, salary, age) VALUES (1, 'Alex123', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu', 3456, 33);
INSERT INTO User (id, username, password, salary, age) VALUES (2, 'Tom234', '$2a$04$PCIX2hYrve38M7eOcqAbCO9UqjYg7gfFNpKsinAxh99nms9e.8HwK', 7823, 23);
INSERT INTO User (id, username, password, salary, age) VALUES (3, 'Adam', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu', 4234, 45);
